# Set theme
remote_theme: emiliobellini/alembic@v4.1.0

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://emiliobellini.github.io/'
baseurl: ''
title: 'Emilio Bellini'
description: 'This is my website. You can find some info about my job, my research interests and some link to find my papers and social media.'
permalink: pretty
logo: '/assets/logos/favicon.ico'
email: 'emilio.bellini-at-sissa.it'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research & Publications
  url: /research_and_publications/
- title: Software
  url: /software/
- title: Contact
  url: /contact/
# - title: Blog
#   url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections (uncomment if blog)
# collections:
#   posts:
#     title: Posts
#     output: true
#     description: "My thoughts and ideas"
#     feature_text: |
#       Welcome to my blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


links:
  arxiv: https://arxiv.org/search/?query=bellini+emilio&searchtype=author&abstracts=show&order=-announced_date_first&size=50
  ads: https://ui.adsabs.harvard.edu/search/q=orcid%3A%220000-0003-4762-0795%22&sort=date%20desc%2C%20bibcode%20desc&p_=0
  inspire: http://inspirehep.net/search?ln=en&p=find+a+e.bellini.1&of=hb&action_search=Search&sf=earliestdate&so=d
  google-scholar: https://scholar.google.co.uk/citations?user=N16POPgAAAAJ&hl=en&oi=sra
  orcid: https://orcid.org/0000-0003-4762-0795
  researcherid: https://publons.com/researcher/1954383/emilio-bellini/
  researchgate: https://www.researchgate.net/profile/Emilio_Bellini
  linkedin: https://www.linkedin.com/in/emilio-bellini/
  github: https://github.com/emiliobellini/
  gitlab: https://gitlab.com/emilio.bellini
  link: https://emiliobellini.github.io/
