# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
# paginate: 2 # jekyll-paginate > items per page
# paginate_path: blog/page:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: EmilioBellini # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Emilio Bellini # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/emilio-bellini/
    - https://www.researchgate.net/profile/Emilio_Bellini
    - https://github.com/emiliobellini
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Rome # Timezone for blog posts and alike

# 5. Collections
# collections:
#   posts:
#     title: Posts # Needed for Siteleaf
#     output: true
#     description: "My thoughts and ideas" # The post list page content
#     feature_text: |
#       Welcome to the blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       image: "/assets/back.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Emilio Bellini" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/favicon.ico" # Site logo, also used in jekyll-seo-tag
description: "This is my website. You can find some info about my job, my research interests and some link to find my papers and social media." # Site description and default description, also used in jekyll-seo-tag
url: "https://emiliobellini.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/emiliobellini/emiliobellini.github.io"
email: "emilio.bellini-at-unige.ch"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Research & Publications
  url: /research_and_publications/
- title: Software
  url: /software/
- title: Contact
  url: /contact/

navigation_footer:
- title: Adapted from Alembic theme
  url: https://alembic.darn.es/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/emilio-bellini/
  GitHub: https://github.com/emiliobellini/
  link: https://emiliobellini.github.io/
#   Twitter: https://twitter.com/DavidDarnes
#   RSS: /feed.xml

links:
  arxiv: https://arxiv.org/search/?query=bellini+emilio&searchtype=author&abstracts=show&order=-announced_date_first&size=50
  ads: https://ui.adsabs.harvard.edu/search/q=orcid%3A%220000-0003-4762-0795%22&sort=date%20desc%2C%20bibcode%20desc&p_=0
  inspire: http://inspirehep.net/search?ln=en&p=find+a+e.bellini.1&of=hb&action_search=Search&sf=earliestdate&so=d
  google-scholar: https://scholar.google.co.uk/citations?user=N16POPgAAAAJ&hl=en&oi=sra
  orcid: https://orcid.org/0000-0003-4762-0795
  researcherid: https://publons.com/researcher/1954383/emilio-bellini/
  researchgate: https://www.researchgate.net/profile/Emilio_Bellini
  linkedin: https://www.linkedin.com/in/emilio-bellini/
  github: https://github.com/emiliobellini/
  link: https://emiliobellini.github.io/
#
# sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#   Twitter: "#0d94e7"
#   facebook: "#3B5998"
#   Email: true
